<a href="https://colab.research.google.com/github/mahirezuhalozdemir/Deep_Learning_Tutorial/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**CHECK NUMPY VERSION**

In [ ]:
#check numpy version
np.__version__

'1.25.2'

**CREATE ARRAY**

In [ ]:
#create numpy array
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#create single-dimension array
arr = np.array(29)
arr

array(29)

In [ ]:
#create 2-D array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#create 3-D array
arr = np.array([
              [[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]]
              ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
#create 0 array
arr = np.zeros((3,1))
arr

array([[0.],
       [0.],
       [0.]])

In [ ]:
#create 1 array
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#create numpy array with constant number
arr = np.full((2,3),9)
arr

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
#numpy array range
arr = np.array(range(2,20,2))
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#create array within the specified range
arr = np.linspace(2,5,3)
arr

array([2. , 3.5, 5. ])

**CHECK NUMBER OF DIMENSION**

In [ ]:
#check number of dimension
arr.ndim
#ndim prints number of dimension of array

3

In [ ]:
#set specific number of dimension
arr = np.array([1, 2, 3, 4], ndmin=5)
arr.ndim

5

**CHECK SIZE OF ARRAY**

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.size

4

**CHECK SHAPE OF ARRAY**

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.shape #return shape of array

(4,)

**CHANGE SHAPE OF ARRAY**

In [ ]:
#reshape of array
arr = np.array([1,2,3,4,5,6])
reshp_arr = arr.reshape(3,2)
reshp_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

**CHECK DATA TYPE OF ARRAY**

In [ ]:
#return type of the array
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [ ]:
#return type of the array (include different types of elements)
arr = np.array([1, 2, 3, 4, 5.0])
arr.dtype

dtype('float64')

In [ ]:
#create an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')
arr.dtype
# i for integer
# u for unsigned integer
# f for float
# S for zero-terminated bytes
# U for Unicode string

dtype('S1')

**CHANGE DATA TYPE OF ARRAY**

In [ ]:
#change data type of array
arr = np.array([1.1, 2.1, 3.1])
int_arr = arr.astype('i')
#int_arr = arr.astype(int)
int_arr

array([1, 2, 3], dtype=int32)

In [ ]:
arr = np.array([1, 2, 3])
float_arr = arr.astype(float)
float_arr

array([1., 2., 3.])

**INDEXING**

In [ ]:
#array indexing
arr = np.array([1,2,3,4,5])
arr[0]

1

In [ ]:
#multi-dimension array indexing
arr = np.array([[1,2,3],[4,5,6]])
arr[1,0] #second row, first column

4

In [ ]:
#multi-dimension array indexing
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
    ])
arr[0,1,1] #second element of the second row of the first array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#negative indexing
arr = np.array([[1,2,3],[4,5,6]])
arr[1,-1] # last element of the second row

6

**SLICING**

In [ ]:
#slice elements from index 1 to 3
arr = np.array([1,2,3,4,5,6])
arr[1:3]

array([2, 3])

In [ ]:
#slice elements from index 1 to end of the array
arr = np.array([1,2,3,4,5,6])
arr[1:]

array([2, 3, 4, 5, 6])

In [ ]:
#slice elements from beginnig of the array to 3
arr = np.array([1,2,3,4,5,6])
arr[:3]

array([1, 2, 3])

In [ ]:
#negative slicing
#indexing from end of the array
arr = np.array([1,2,3,4,5,6])
arr[-3:-1]

array([4, 5])

**STEP BY STEP SLICING**

In [ ]:
#slicing with step size
arr = np.array([1,2,3,4,5,6])
arr[1:6:2]

array([2, 4, 6])

In [ ]:
#return elements in 2 steps
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
#2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1,1:4] #elements from first index to the 4th index of the second arrays

array([7, 8, 9])

In [ ]:
#2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 2]
#second element of arrays from first to the third

[3 8]


**COPY ARRAY**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
copy_arr[3] = 29
print('copy array: ', copy_arr)
print('array: ', arr)

copy array:  [ 1  2  3 29  5]
array:  [1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
arr[3] = 29
print('copy array: ', copy_arr)
print('array: ', arr)

copy array:  [1 2 3 4 5]
array:  [ 1  2  3 29  5]


**MAKE A VIEW OF ARRAY**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
arr[0] = 42
print('view array: ', view_arr)
print('array: ', arr)

view array:  [42  2  3  4  5]
array:  [42  2  3  4  5]


**ARRAY ITERATING**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

for i in arr:
  print(i)

1
2
3
4
5


In [ ]:
#2-D array
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#3-D array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

for i in arr:
  for j in i:
    for k in j:
      print(k)

**SPLIT ARRAY**

In [ ]:
#split array parts
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 3)
#split the array in 3 parts
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

**WHERE COMMAND FOR SEARCHING**

In [ ]:
#searching in array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
index = np.where(arr == 4)
index

(array([3]),)

In [ ]:
#searching in array with mode operate
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])
index = np.where(arr % 4 == 0)
index

(array([3, 7]),)